/*
 * Move2Kube API
 * This is a documentation of the Move2Kube REST API. All API calls expect the `Authorization: Bearer <access-token>` HTTP header unless specified otherwise. The access token can be obtained in the same way as OAuth 2.0 using the token endpoint in the admin section. 
 *
 * The version of the OpenAPI document: v1.0.0
 * Contact: move2kube-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.konveyor.move.api;

import com.konveyor.move.ApiCallback;
import com.konveyor.move.ApiClient;
import com.konveyor.move.ApiException;
import com.konveyor.move.ApiResponse;
import com.konveyor.move.Configuration;
import com.konveyor.move.Pair;
import com.konveyor.move.ProgressRequestBody;
import com.konveyor.move.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.konveyor.move.client.model.GetPlan200Response;
import com.konveyor.move.client.model.UpdatePlanRequest;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.core.GenericType;

public class PlanApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public PlanApi() {
        this(Configuration.getDefaultApiClient());
    }

    public PlanApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for deletePlan
     * @param workspaceId ID of the workspace the project is in. (required)
     * @param projectId ID of the project to delete the plan from. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Deleted. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authorization header is missing or invalid. </td><td>  * WWW_Authenticate -  <br>  </td></tr>
        <tr><td> 403 </td><td> Don&#39;t have authorization to delete the plan for this project. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Workspace or project not found. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deletePlanCall(String workspaceId, String projectId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/workspaces/{workspace-id}/projects/{project-id}/plan"
            .replace("{" + "workspace-id" + "}", localVarApiClient.escapeString(workspaceId.toString()))
            .replace("{" + "project-id" + "}", localVarApiClient.escapeString(projectId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deletePlanValidateBeforeCall(String workspaceId, String projectId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'workspaceId' is set
        if (workspaceId == null) {
            throw new ApiException("Missing the required parameter 'workspaceId' when calling deletePlan(Async)");
        }

        // verify the required parameter 'projectId' is set
        if (projectId == null) {
            throw new ApiException("Missing the required parameter 'projectId' when calling deletePlan(Async)");
        }

        return deletePlanCall(workspaceId, projectId, _callback);

    }

    /**
     * Delete the current plan for the project.
     * Delete the current plan for the project.
     * @param workspaceId ID of the workspace the project is in. (required)
     * @param projectId ID of the project to delete the plan from. (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Deleted. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authorization header is missing or invalid. </td><td>  * WWW_Authenticate -  <br>  </td></tr>
        <tr><td> 403 </td><td> Don&#39;t have authorization to delete the plan for this project. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Workspace or project not found. </td><td>  -  </td></tr>
     </table>
     */
    public void deletePlan(String workspaceId, String projectId) throws ApiException {
        deletePlanWithHttpInfo(workspaceId, projectId);
    }

    /**
     * Delete the current plan for the project.
     * Delete the current plan for the project.
     * @param workspaceId ID of the workspace the project is in. (required)
     * @param projectId ID of the project to delete the plan from. (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Deleted. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authorization header is missing or invalid. </td><td>  * WWW_Authenticate -  <br>  </td></tr>
        <tr><td> 403 </td><td> Don&#39;t have authorization to delete the plan for this project. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Workspace or project not found. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> deletePlanWithHttpInfo(String workspaceId, String projectId) throws ApiException {
        okhttp3.Call localVarCall = deletePlanValidateBeforeCall(workspaceId, projectId, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Delete the current plan for the project. (asynchronously)
     * Delete the current plan for the project.
     * @param workspaceId ID of the workspace the project is in. (required)
     * @param projectId ID of the project to delete the plan from. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Deleted. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authorization header is missing or invalid. </td><td>  * WWW_Authenticate -  <br>  </td></tr>
        <tr><td> 403 </td><td> Don&#39;t have authorization to delete the plan for this project. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Workspace or project not found. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deletePlanAsync(String workspaceId, String projectId, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = deletePlanValidateBeforeCall(workspaceId, projectId, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for getPlan
     * @param workspaceId ID of the workspace the project is in. (required)
     * @param projectId ID of the project to get the plan from. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Accepted. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid format or validation error. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authorization header is missing or invalid. </td><td>  * WWW_Authenticate -  <br>  </td></tr>
        <tr><td> 403 </td><td> Don&#39;t have authorization to start planning for this project. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Workspace or project not found. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict, because planning is already on-going for this project. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getPlanCall(String workspaceId, String projectId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/workspaces/{workspace-id}/projects/{project-id}/plan"
            .replace("{" + "workspace-id" + "}", localVarApiClient.escapeString(workspaceId.toString()))
            .replace("{" + "project-id" + "}", localVarApiClient.escapeString(projectId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getPlanValidateBeforeCall(String workspaceId, String projectId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'workspaceId' is set
        if (workspaceId == null) {
            throw new ApiException("Missing the required parameter 'workspaceId' when calling getPlan(Async)");
        }

        // verify the required parameter 'projectId' is set
        if (projectId == null) {
            throw new ApiException("Missing the required parameter 'projectId' when calling getPlan(Async)");
        }

        return getPlanCall(workspaceId, projectId, _callback);

    }

    /**
     * Get the plan file.
     * Get the plan file.
     * @param workspaceId ID of the workspace the project is in. (required)
     * @param projectId ID of the project to get the plan from. (required)
     * @return GetPlan200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Accepted. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid format or validation error. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authorization header is missing or invalid. </td><td>  * WWW_Authenticate -  <br>  </td></tr>
        <tr><td> 403 </td><td> Don&#39;t have authorization to start planning for this project. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Workspace or project not found. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict, because planning is already on-going for this project. </td><td>  -  </td></tr>
     </table>
     */
    public GetPlan200Response getPlan(String workspaceId, String projectId) throws ApiException {
        ApiResponse<GetPlan200Response> localVarResp = getPlanWithHttpInfo(workspaceId, projectId);
        return localVarResp.getData();
    }

    /**
     * Get the plan file.
     * Get the plan file.
     * @param workspaceId ID of the workspace the project is in. (required)
     * @param projectId ID of the project to get the plan from. (required)
     * @return ApiResponse&lt;GetPlan200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Accepted. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid format or validation error. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authorization header is missing or invalid. </td><td>  * WWW_Authenticate -  <br>  </td></tr>
        <tr><td> 403 </td><td> Don&#39;t have authorization to start planning for this project. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Workspace or project not found. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict, because planning is already on-going for this project. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GetPlan200Response> getPlanWithHttpInfo(String workspaceId, String projectId) throws ApiException {
        okhttp3.Call localVarCall = getPlanValidateBeforeCall(workspaceId, projectId, null);
        Type localVarReturnType = new TypeToken<GetPlan200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get the plan file. (asynchronously)
     * Get the plan file.
     * @param workspaceId ID of the workspace the project is in. (required)
     * @param projectId ID of the project to get the plan from. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Accepted. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid format or validation error. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authorization header is missing or invalid. </td><td>  * WWW_Authenticate -  <br>  </td></tr>
        <tr><td> 403 </td><td> Don&#39;t have authorization to start planning for this project. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Workspace or project not found. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict, because planning is already on-going for this project. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getPlanAsync(String workspaceId, String projectId, final ApiCallback<GetPlan200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = getPlanValidateBeforeCall(workspaceId, projectId, _callback);
        Type localVarReturnType = new TypeToken<GetPlan200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for startPlanning
     * @param workspaceId ID of the workspace the project is in. (required)
     * @param projectId ID of the project to start planning in. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 202 </td><td> Accepted. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid format or validation error. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authorization header is missing or invalid. </td><td>  * WWW_Authenticate -  <br>  </td></tr>
        <tr><td> 403 </td><td> Don&#39;t have authorization to start planning for this project. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Workspace or project not found. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call startPlanningCall(String workspaceId, String projectId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/workspaces/{workspace-id}/projects/{project-id}/plan"
            .replace("{" + "workspace-id" + "}", localVarApiClient.escapeString(workspaceId.toString()))
            .replace("{" + "project-id" + "}", localVarApiClient.escapeString(projectId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call startPlanningValidateBeforeCall(String workspaceId, String projectId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'workspaceId' is set
        if (workspaceId == null) {
            throw new ApiException("Missing the required parameter 'workspaceId' when calling startPlanning(Async)");
        }

        // verify the required parameter 'projectId' is set
        if (projectId == null) {
            throw new ApiException("Missing the required parameter 'projectId' when calling startPlanning(Async)");
        }

        return startPlanningCall(workspaceId, projectId, _callback);

    }

    /**
     * Start planning on this project&#39;s inputs.
     * Start planning on this project&#39;s inputs.
     * @param workspaceId ID of the workspace the project is in. (required)
     * @param projectId ID of the project to start planning in. (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 202 </td><td> Accepted. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid format or validation error. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authorization header is missing or invalid. </td><td>  * WWW_Authenticate -  <br>  </td></tr>
        <tr><td> 403 </td><td> Don&#39;t have authorization to start planning for this project. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Workspace or project not found. </td><td>  -  </td></tr>
     </table>
     */
    public void startPlanning(String workspaceId, String projectId) throws ApiException {
        startPlanningWithHttpInfo(workspaceId, projectId);
    }

    /**
     * Start planning on this project&#39;s inputs.
     * Start planning on this project&#39;s inputs.
     * @param workspaceId ID of the workspace the project is in. (required)
     * @param projectId ID of the project to start planning in. (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 202 </td><td> Accepted. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid format or validation error. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authorization header is missing or invalid. </td><td>  * WWW_Authenticate -  <br>  </td></tr>
        <tr><td> 403 </td><td> Don&#39;t have authorization to start planning for this project. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Workspace or project not found. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> startPlanningWithHttpInfo(String workspaceId, String projectId) throws ApiException {
        okhttp3.Call localVarCall = startPlanningValidateBeforeCall(workspaceId, projectId, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Start planning on this project&#39;s inputs. (asynchronously)
     * Start planning on this project&#39;s inputs.
     * @param workspaceId ID of the workspace the project is in. (required)
     * @param projectId ID of the project to start planning in. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 202 </td><td> Accepted. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid format or validation error. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authorization header is missing or invalid. </td><td>  * WWW_Authenticate -  <br>  </td></tr>
        <tr><td> 403 </td><td> Don&#39;t have authorization to start planning for this project. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Workspace or project not found. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call startPlanningAsync(String workspaceId, String projectId, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = startPlanningValidateBeforeCall(workspaceId, projectId, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for updatePlan
     * @param workspaceId ID of the workspace the project is in. (required)
     * @param projectId ID of the project to update the plan for. (required)
     * @param body  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Accepted. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid format or validation error. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authorization header is missing or invalid. </td><td>  * WWW_Authenticate -  <br>  </td></tr>
        <tr><td> 403 </td><td> Don&#39;t have authorization to update the plan for this project. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Workspace or project not found. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updatePlanCall(String workspaceId, String projectId, UpdatePlanRequest body, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = body;

        // create path and map variables
        String localVarPath = "/workspaces/{workspace-id}/projects/{project-id}/plan"
            .replace("{" + "workspace-id" + "}", localVarApiClient.escapeString(workspaceId.toString()))
            .replace("{" + "project-id" + "}", localVarApiClient.escapeString(projectId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updatePlanValidateBeforeCall(String workspaceId, String projectId, UpdatePlanRequest body, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'workspaceId' is set
        if (workspaceId == null) {
            throw new ApiException("Missing the required parameter 'workspaceId' when calling updatePlan(Async)");
        }

        // verify the required parameter 'projectId' is set
        if (projectId == null) {
            throw new ApiException("Missing the required parameter 'projectId' when calling updatePlan(Async)");
        }

        // verify the required parameter 'body' is set
        if (body == null) {
            throw new ApiException("Missing the required parameter 'body' when calling updatePlan(Async)");
        }

        return updatePlanCall(workspaceId, projectId, body, _callback);

    }

    /**
     * Update the plan for this project.
     * Update the plan for this project.
     * @param workspaceId ID of the workspace the project is in. (required)
     * @param projectId ID of the project to update the plan for. (required)
     * @param body  (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Accepted. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid format or validation error. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authorization header is missing or invalid. </td><td>  * WWW_Authenticate -  <br>  </td></tr>
        <tr><td> 403 </td><td> Don&#39;t have authorization to update the plan for this project. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Workspace or project not found. </td><td>  -  </td></tr>
     </table>
     */
    public void updatePlan(String workspaceId, String projectId, UpdatePlanRequest body) throws ApiException {
        updatePlanWithHttpInfo(workspaceId, projectId, body);
    }

    /**
     * Update the plan for this project.
     * Update the plan for this project.
     * @param workspaceId ID of the workspace the project is in. (required)
     * @param projectId ID of the project to update the plan for. (required)
     * @param body  (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Accepted. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid format or validation error. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authorization header is missing or invalid. </td><td>  * WWW_Authenticate -  <br>  </td></tr>
        <tr><td> 403 </td><td> Don&#39;t have authorization to update the plan for this project. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Workspace or project not found. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> updatePlanWithHttpInfo(String workspaceId, String projectId, UpdatePlanRequest body) throws ApiException {
        okhttp3.Call localVarCall = updatePlanValidateBeforeCall(workspaceId, projectId, body, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Update the plan for this project. (asynchronously)
     * Update the plan for this project.
     * @param workspaceId ID of the workspace the project is in. (required)
     * @param projectId ID of the project to update the plan for. (required)
     * @param body  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Accepted. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid format or validation error. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authorization header is missing or invalid. </td><td>  * WWW_Authenticate -  <br>  </td></tr>
        <tr><td> 403 </td><td> Don&#39;t have authorization to update the plan for this project. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Workspace or project not found. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updatePlanAsync(String workspaceId, String projectId, UpdatePlanRequest body, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = updatePlanValidateBeforeCall(workspaceId, projectId, body, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
}
