/*
 * Move2Kube API
 * This is a documentation of the Move2Kube REST API. All API calls expect the `Authorization: Bearer <access-token>` HTTP header unless specified otherwise. The access token can be obtained in the same way as OAuth 2.0 using the token endpoint in the admin section. 
 *
 * The version of the OpenAPI document: v1.0.0
 * Contact: move2kube-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.Error;
import org.openapitools.client.model.GetCurrentQuestion200Response;
import org.openapitools.client.model.PostAnswerToQuestionRequest;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.core.GenericType;

public class QaApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public QaApi() {
        this(Configuration.getDefaultApiClient());
    }

    public QaApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for getCurrentQuestion
     * @param workspaceId ID of the workspace the project is in. (required)
     * @param projectId ID of the project the output is in. (required)
     * @param outputId ID of the output whose transformation is on-going. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success. </td><td>  -  </td></tr>
        <tr><td> 204 </td><td> All questions have finished. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authorization header is missing or invalid. </td><td>  * WWW_Authenticate -  <br>  </td></tr>
        <tr><td> 403 </td><td> Don&#39;t have authorization to get this project output. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Workspace, project or output not found. Might also be returned once the transformation has finished. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getCurrentQuestionCall(String workspaceId, String projectId, String outputId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/workspaces/{workspace-id}/projects/{project-id}/outputs/{output-id}/problems/current"
            .replace("{" + "workspace-id" + "}", localVarApiClient.escapeString(workspaceId.toString()))
            .replace("{" + "project-id" + "}", localVarApiClient.escapeString(projectId.toString()))
            .replace("{" + "output-id" + "}", localVarApiClient.escapeString(outputId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getCurrentQuestionValidateBeforeCall(String workspaceId, String projectId, String outputId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'workspaceId' is set
        if (workspaceId == null) {
            throw new ApiException("Missing the required parameter 'workspaceId' when calling getCurrentQuestion(Async)");
        }

        // verify the required parameter 'projectId' is set
        if (projectId == null) {
            throw new ApiException("Missing the required parameter 'projectId' when calling getCurrentQuestion(Async)");
        }

        // verify the required parameter 'outputId' is set
        if (outputId == null) {
            throw new ApiException("Missing the required parameter 'outputId' when calling getCurrentQuestion(Async)");
        }

        return getCurrentQuestionCall(workspaceId, projectId, outputId, _callback);

    }

    /**
     * Get the current question that needs to be answered for the transformation to proceed.
     * Get the current question that needs to be answered for the transformation to proceed.
     * @param workspaceId ID of the workspace the project is in. (required)
     * @param projectId ID of the project the output is in. (required)
     * @param outputId ID of the output whose transformation is on-going. (required)
     * @return GetCurrentQuestion200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success. </td><td>  -  </td></tr>
        <tr><td> 204 </td><td> All questions have finished. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authorization header is missing or invalid. </td><td>  * WWW_Authenticate -  <br>  </td></tr>
        <tr><td> 403 </td><td> Don&#39;t have authorization to get this project output. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Workspace, project or output not found. Might also be returned once the transformation has finished. </td><td>  -  </td></tr>
     </table>
     */
    public GetCurrentQuestion200Response getCurrentQuestion(String workspaceId, String projectId, String outputId) throws ApiException {
        ApiResponse<GetCurrentQuestion200Response> localVarResp = getCurrentQuestionWithHttpInfo(workspaceId, projectId, outputId);
        return localVarResp.getData();
    }

    /**
     * Get the current question that needs to be answered for the transformation to proceed.
     * Get the current question that needs to be answered for the transformation to proceed.
     * @param workspaceId ID of the workspace the project is in. (required)
     * @param projectId ID of the project the output is in. (required)
     * @param outputId ID of the output whose transformation is on-going. (required)
     * @return ApiResponse&lt;GetCurrentQuestion200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success. </td><td>  -  </td></tr>
        <tr><td> 204 </td><td> All questions have finished. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authorization header is missing or invalid. </td><td>  * WWW_Authenticate -  <br>  </td></tr>
        <tr><td> 403 </td><td> Don&#39;t have authorization to get this project output. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Workspace, project or output not found. Might also be returned once the transformation has finished. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GetCurrentQuestion200Response> getCurrentQuestionWithHttpInfo(String workspaceId, String projectId, String outputId) throws ApiException {
        okhttp3.Call localVarCall = getCurrentQuestionValidateBeforeCall(workspaceId, projectId, outputId, null);
        Type localVarReturnType = new TypeToken<GetCurrentQuestion200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get the current question that needs to be answered for the transformation to proceed. (asynchronously)
     * Get the current question that needs to be answered for the transformation to proceed.
     * @param workspaceId ID of the workspace the project is in. (required)
     * @param projectId ID of the project the output is in. (required)
     * @param outputId ID of the output whose transformation is on-going. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success. </td><td>  -  </td></tr>
        <tr><td> 204 </td><td> All questions have finished. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authorization header is missing or invalid. </td><td>  * WWW_Authenticate -  <br>  </td></tr>
        <tr><td> 403 </td><td> Don&#39;t have authorization to get this project output. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Workspace, project or output not found. Might also be returned once the transformation has finished. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getCurrentQuestionAsync(String workspaceId, String projectId, String outputId, final ApiCallback<GetCurrentQuestion200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = getCurrentQuestionValidateBeforeCall(workspaceId, projectId, outputId, _callback);
        Type localVarReturnType = new TypeToken<GetCurrentQuestion200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for postAnswerToQuestion
     * @param workspaceId ID of the workspace the project is in. (required)
     * @param projectId ID of the project to start the transformation for. (required)
     * @param outputId ID of the output whose transformation is on-going. (required)
     * @param body A plan to use for the transformation. (Not required).  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Answer was accepted </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid format or validation error. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authorization header is missing or invalid. </td><td>  * WWW_Authenticate -  <br>  </td></tr>
        <tr><td> 403 </td><td> Don&#39;t have authorization to post an answer to the question for this project output. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Workspace, project, or output not found. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call postAnswerToQuestionCall(String workspaceId, String projectId, String outputId, PostAnswerToQuestionRequest body, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = body;

        // create path and map variables
        String localVarPath = "/workspaces/{workspace-id}/projects/{project-id}/outputs/{output-id}/problems/current/solution"
            .replace("{" + "workspace-id" + "}", localVarApiClient.escapeString(workspaceId.toString()))
            .replace("{" + "project-id" + "}", localVarApiClient.escapeString(projectId.toString()))
            .replace("{" + "output-id" + "}", localVarApiClient.escapeString(outputId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call postAnswerToQuestionValidateBeforeCall(String workspaceId, String projectId, String outputId, PostAnswerToQuestionRequest body, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'workspaceId' is set
        if (workspaceId == null) {
            throw new ApiException("Missing the required parameter 'workspaceId' when calling postAnswerToQuestion(Async)");
        }

        // verify the required parameter 'projectId' is set
        if (projectId == null) {
            throw new ApiException("Missing the required parameter 'projectId' when calling postAnswerToQuestion(Async)");
        }

        // verify the required parameter 'outputId' is set
        if (outputId == null) {
            throw new ApiException("Missing the required parameter 'outputId' when calling postAnswerToQuestion(Async)");
        }

        // verify the required parameter 'body' is set
        if (body == null) {
            throw new ApiException("Missing the required parameter 'body' when calling postAnswerToQuestion(Async)");
        }

        return postAnswerToQuestionCall(workspaceId, projectId, outputId, body, _callback);

    }

    /**
     * Post the answer to the current question for an on-going transformation given by the ID.
     * Post the answer to the current question for an on-going transformation given by the ID.
     * @param workspaceId ID of the workspace the project is in. (required)
     * @param projectId ID of the project to start the transformation for. (required)
     * @param outputId ID of the output whose transformation is on-going. (required)
     * @param body A plan to use for the transformation. (Not required).  (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Answer was accepted </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid format or validation error. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authorization header is missing or invalid. </td><td>  * WWW_Authenticate -  <br>  </td></tr>
        <tr><td> 403 </td><td> Don&#39;t have authorization to post an answer to the question for this project output. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Workspace, project, or output not found. </td><td>  -  </td></tr>
     </table>
     */
    public void postAnswerToQuestion(String workspaceId, String projectId, String outputId, PostAnswerToQuestionRequest body) throws ApiException {
        postAnswerToQuestionWithHttpInfo(workspaceId, projectId, outputId, body);
    }

    /**
     * Post the answer to the current question for an on-going transformation given by the ID.
     * Post the answer to the current question for an on-going transformation given by the ID.
     * @param workspaceId ID of the workspace the project is in. (required)
     * @param projectId ID of the project to start the transformation for. (required)
     * @param outputId ID of the output whose transformation is on-going. (required)
     * @param body A plan to use for the transformation. (Not required).  (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Answer was accepted </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid format or validation error. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authorization header is missing or invalid. </td><td>  * WWW_Authenticate -  <br>  </td></tr>
        <tr><td> 403 </td><td> Don&#39;t have authorization to post an answer to the question for this project output. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Workspace, project, or output not found. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> postAnswerToQuestionWithHttpInfo(String workspaceId, String projectId, String outputId, PostAnswerToQuestionRequest body) throws ApiException {
        okhttp3.Call localVarCall = postAnswerToQuestionValidateBeforeCall(workspaceId, projectId, outputId, body, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Post the answer to the current question for an on-going transformation given by the ID. (asynchronously)
     * Post the answer to the current question for an on-going transformation given by the ID.
     * @param workspaceId ID of the workspace the project is in. (required)
     * @param projectId ID of the project to start the transformation for. (required)
     * @param outputId ID of the output whose transformation is on-going. (required)
     * @param body A plan to use for the transformation. (Not required).  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Answer was accepted </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid format or validation error. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authorization header is missing or invalid. </td><td>  * WWW_Authenticate -  <br>  </td></tr>
        <tr><td> 403 </td><td> Don&#39;t have authorization to post an answer to the question for this project output. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Workspace, project, or output not found. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call postAnswerToQuestionAsync(String workspaceId, String projectId, String outputId, PostAnswerToQuestionRequest body, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = postAnswerToQuestionValidateBeforeCall(workspaceId, projectId, outputId, body, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
}
