/*
 * Move2Kube API
 * This is a documentation of the Move2Kube REST API. All API calls expect the `Authorization: Bearer <access-token>` HTTP header unless specified otherwise. The access token can be obtained in the same way as OAuth 2.0 using the token endpoint in the admin section. 
 *
 * The version of the OpenAPI document: v1.0.0
 * Contact: move2kube-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Error;
import org.openapitools.client.model.GetCurrentQuestion200Response;
import org.openapitools.client.model.PostAnswerToQuestionRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for QaApi
 */
@Disabled
public class QaApiTest {

    private final QaApi api = new QaApi();

    /**
     * Get the current question that needs to be answered for the transformation to proceed.
     *
     * Get the current question that needs to be answered for the transformation to proceed.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCurrentQuestionTest() throws ApiException {
        String workspaceId = null;
        String projectId = null;
        String outputId = null;
        GetCurrentQuestion200Response response = api.getCurrentQuestion(workspaceId, projectId, outputId);
        // TODO: test validations
    }

    /**
     * Post the answer to the current question for an on-going transformation given by the ID.
     *
     * Post the answer to the current question for an on-going transformation given by the ID.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postAnswerToQuestionTest() throws ApiException {
        String workspaceId = null;
        String projectId = null;
        String outputId = null;
        PostAnswerToQuestionRequest body = null;
        api.postAnswerToQuestion(workspaceId, projectId, outputId, body);
        // TODO: test validations
    }

}
