/*
 * Move2Kube API
 * This is a documentation of the Move2Kube REST API. All API calls expect the `Authorization: Bearer <access-token>` HTTP header unless specified otherwise. The access token can be obtained in the same way as OAuth 2.0 using the token endpoint in the admin section. 
 *
 * The version of the OpenAPI document: v1.0.0
 * Contact: move2kube-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.parodos.move2kube.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PostAnswerToQuestionRequest
 */
public class PostAnswerToQuestionRequestTest {
    private final PostAnswerToQuestionRequest model = new PostAnswerToQuestionRequest();

    /**
     * Model tests for PostAnswerToQuestionRequest
     */
    @Test
    public void testPostAnswerToQuestionRequest() {
        // TODO: test PostAnswerToQuestionRequest
    }

    /**
     * Test the property 'solution'
     */
    @Test
    public void solutionTest() {
        // TODO: test solution
    }

}
